name: kakao-login
app: node@22 # ✅ Node.js 최신 버전 (16 → 22)
options:
  git:
    branch: main
    url: https://github.com/JeongHyeon-Han/Forher_test.git
  env:
    - name: NODE_ENV
      value: production
    - name: PORT
      value: 4000
    - name: DOMAIN
      value: https://shildforher.life
    - name: SESSION_SECRET
      value: mySuperSecretSessionKey
    - name: DB_HOST
      value: project-db-campus.smhrd.com
    - name: DB_USER
      value: campus_2SIS_health1_p2_2
    - name: DB_PASSWORD
      value: smhrd2
    - name: DB_NAME
      value: campus_2SIS_health1_p2_2
    - name: DB_PORT
      value: 3307
    - name: KAKAO_CLIENT_ID
      value: 5a1cd175986f8f7e5c8828ea09bb0e7e
    - name: KAKAO_CLIENT_SECRET
      value: 2QhUCBnr3LSRZlqrAbmcca8B8ydl5HJN
    - name: KAKAO_REDIRECT_URI
      value: https://shildforher.life/redirect
    - name: KAKAO_TOKEN_URI
      value: https://kauth.kakao.com/oauth/token
    - name: KAKAO_API_HOST
      value: https://kapi.kakao.com
  install: npm ci --production
  ports: 4000 # ✅ 포트 3000 → 4000 (env와 일치)
  start: node app.js # ✅ npm start 대신 node app.js로 명시
